/* This file is automatically generated by Payload CMS for client-side admin components */
/* Last updated: 2025-12-19 - React 19 / Payload 3.0 migration */

import { VercelBlobClientUploadHandler } from '@payloadcms/storage-vercel-blob/client'
import { RichTextCell } from '@payloadcms/richtext-lexical/client'
import { RichTextField } from '@payloadcms/richtext-lexical/client'
import { lexicalEditor } from '@payloadcms/richtext-lexical/client'

export const importMap = {
  '@payloadcms/storage-vercel-blob/client#VercelBlobClientUploadHandler': VercelBlobClientUploadHandler,
  '@payloadcms/richtext-lexical/client#RichTextCell': RichTextCell,
  '@payloadcms/richtext-lexical/client#RichTextField': RichTextField,
  '@payloadcms/richtext-lexical/client#lexicalEditor': lexicalEditor,
}