fragment LandingPageParts on LandingPage {
	__typename
	header {
		__typename
		siteName
		navigation {
			__typename
			label
			href
		}
	}
	hero {
		__typename
		title
		description
		primaryButtonText
		secondaryButtonText
		videoPlaceholder
		videoPlaceholderAlt
	}
	trustIndicators {
		__typename
		sectionTitle
		sectionDescription
		indicators {
			__typename
			icon
			title
			description
		}
	}
	testimonials {
		__typename
		sectionTitle
		sectionSubtitle
		testimonials {
			__typename
			quote
			author
			role
			avatar
			rating
		}
	}
	services {
		__typename
		sectionTitle
		sectionDescription
		services {
			__typename
			title
			description
			icon
			features {
				__typename
				feature
			}
			ctaText
			ctaLink
		}
	}
	results {
		__typename
		sectionTitle
		sectionDescription
		statistics {
			__typename
			number
			label
			description
			icon
		}
	}
	contact {
		__typename
		sectionTitle
		sectionDescription
		formTitle
		formDescription
		submitButtonText
		contactInfo {
			__typename
			email
			phone
			address
		}
	}
	footer {
		__typename
		companyName
		description
		footerSections {
			__typename
			title
			links {
				__typename
				label
				href
			}
		}
		copyrightText
	}
}

fragment SeasonalContentParts on SeasonalContent {
	__typename
	seasons {
		__typename
		spring {
			__typename
			title
			description
			ctaText
			focusArea
			bgGradient
		}
		summer {
			__typename
			title
			description
			ctaText
			focusArea
			bgGradient
		}
		autumn {
			__typename
			title
			description
			ctaText
			focusArea
			bgGradient
		}
		winter {
			__typename
			title
			description
			ctaText
			focusArea
			bgGradient
		}
	}
}

fragment PageParts on Page {
	__typename
	title
	description
	body
}

fragment PostParts on Post {
	__typename
	title
	description
	date
	body
}
