/**
 * Do not edit directly, this file was auto-generated.
 */

module.exports = {
	ColorPrimaryBase: '#3f4a7e',
	ColorPrimaryLight: '#5a6b9e',
	ColorPrimaryDark: '#2d3456',
	ColorPrimaryMuted: '#7a88b3',
	ColorSecondaryBase: '#ca9e5b',
	ColorSecondaryLight: '#e5c89a',
	ColorSecondaryDark: '#a67c3d',
	ColorSecondaryMuted: '#d4b480',
	ColorNeutralWhite: '#ffffff',
	ColorNeutralGrey50: '#f9fafb',
	ColorNeutralGrey100: '#f3f4f6',
	ColorNeutralGrey200: '#e5e7eb',
	ColorNeutralGrey400: '#9ca3af',
	ColorNeutralGrey600: '#4b5563',
	ColorNeutralGrey800: '#1f2937',
	ColorNeutralBlack: '#000000',
	ColorSemanticSuccess: '#10b981',
	ColorSemanticError: '#ef4444',
	ColorSemanticWarning: '#f59e0b',
	ColorSemanticInfo: '#3b82f6',
	ColorUiBorder: '#e5e7eb',
	ColorUiOverlay: '#00000080',
	ColorUiDisabled: '#9ca3af',
	ColorUiHover: '#f9fafb',
	ColorUiFocus: '#ca9e5b',
	FontFamilyHeading: 'Playfair Display, Georgia, serif',
	FontFamilyBody: 'Source Serif 4, Georgia, serif',
	FontFamilyTechnical: 'JetBrains Mono, Consolas, monospace',
	FontSizeXs: '12px',
	FontSizeSm: '14px',
	FontSizeBase: '16px',
	FontSizeLg: '18px',
	FontSizeXl: '20px',
	FontSize2xl: '24px',
	FontSize3xl: '32px',
	FontSize4xl: '48px',
	FontSize5xl: '64px',
	FontWeightNormal: 400,
	FontWeightMedium: 500,
	FontWeightSemibold: 600,
	FontWeightBold: 700,
	FontLineHeightTight: 1.2,
	FontLineHeightSnug: 1.4,
	FontLineHeightNormal: 1.5,
	FontLineHeightRelaxed: 1.6,
	FontLetterSpacingTighter: '-0.05em',
	FontLetterSpacingTight: '-0.025em',
	FontLetterSpacingNormal: '0',
	FontLetterSpacingWide: '0.025em',
	FontLetterSpacingWider: '0.05em',
	TypographyHeadingH1: {
		fontFamily: 'Playfair Display, Georgia, serif',
		fontSize: '64px',
		fontWeight: 700,
		lineHeight: 1.2,
		letterSpacing: '-0.05em',
	},
	TypographyHeadingH2: {
		fontFamily: 'Playfair Display, Georgia, serif',
		fontSize: '48px',
		fontWeight: 700,
		lineHeight: 1.2,
		letterSpacing: '-0.025em',
	},
	TypographyHeadingH3: {
		fontFamily: 'Playfair Display, Georgia, serif',
		fontSize: '32px',
		fontWeight: 600,
		lineHeight: 1.4,
		letterSpacing: '-0.025em',
	},
	TypographyHeadingH4: {
		fontFamily: 'Playfair Display, Georgia, serif',
		fontSize: '24px',
		fontWeight: 600,
		lineHeight: 1.4,
		letterSpacing: '0',
	},
	TypographyBodyBase: {
		fontFamily: 'Source Serif 4, Georgia, serif',
		fontSize: '16px',
		fontWeight: 400,
		lineHeight: 1.5,
		letterSpacing: '0',
	},
	TypographyBodyLarge: {
		fontFamily: 'Source Serif 4, Georgia, serif',
		fontSize: '18px',
		fontWeight: 400,
		lineHeight: 1.6,
		letterSpacing: '0',
	},
	TypographyBodySmall: {
		fontFamily: 'Source Serif 4, Georgia, serif',
		fontSize: '14px',
		fontWeight: 400,
		lineHeight: 1.5,
		letterSpacing: '0',
	},
	TypographyTechnicalBase: {
		fontFamily: 'JetBrains Mono, Consolas, monospace',
		fontSize: '16px',
		fontWeight: 500,
		lineHeight: 1.5,
		letterSpacing: '0',
	},
	Spacing0: '0px',
	Spacing1: '4px',
	Spacing2: '8px',
	Spacing3: '12px',
	Spacing4: '16px',
	Spacing5: '20px',
	Spacing6: '24px',
	Spacing8: '32px',
	Spacing10: '40px',
	Spacing12: '48px',
	Spacing16: '64px',
	Spacing20: '80px',
	Spacing24: '96px',
	Spacing32: '128px',
	BorderRadiusNone: '0px',
	BorderRadiusSm: '4px',
	BorderRadiusBase: '8px',
	BorderRadiusMd: '12px',
	BorderRadiusLg: '16px',
	BorderRadiusXl: '24px',
	BorderRadiusFull: '9999px',
	BorderWidthNone: '0px',
	BorderWidthThin: '1px',
	BorderWidthBase: '2px',
	BorderWidthThick: '4px',
};
